from __future__ import annotations

from pathlib import Path


# --- Locations
ROOT_DIR = Path(__file__).parent
ASSETS_DIR = ROOT_DIR.joinpath("assets")

# --- Main window info
WINDOW_WIDTH = 300
WINDOW_HEIGHT = 145
WINDOW_TITLE = "Until Zero"

# --- Timer options
OPTION_TASK = 25
OPTION_SHORT_BREAK = 5
OPTION_LONG_BREAK = 20

# --- Text
SUM_TIMERS_PLACEHOLDER = "0s"
SUM_TIMERS_ERROR = "To the infinity and beyond!"

# --- Fonts
FONT = "CozetteVector"
DEFAULT_SIZE = 12
POMODORO_PREVIEW_SIZE = 10
OPTION_BTN_SIZE = 9
START_BTN_SIZE = 12
CLEAN_BTN_SIZE = 7
TIMER_WINDOW_BTN_SIZE = 12

# --- Color palette
WHITE = "#ffffff"
BLACK = "#000000"
RED = "#c5143e"
DARK_RED = "#c22349"
YELLOW = "#ffe100"
DARK_YELLOW = "#f0ac00"
BLUE = "#10ebeb"
DARK_BLUE = "#27b3b3"
PURPLE = "#9370db"
DARK_PURPLE = "#7b4ddb"

# --- Color config
BACKGROUND_COLOR = YELLOW
TEXT_COLOR = BLACK
INPUT_COLOR = WHITE
INPUT_BG_COLOR = BLACK
PURPLE_BTN_COLOR = WHITE
PURPLE_BTN_BG_COLOR = PURPLE
PURPLE_BTN_BG_ACTIVE_COLOR = DARK_PURPLE
RED_BTN_COLOR = WHITE
RED_BTN_BG_COLOR = DARK_RED
RED_BTN_BG_ACTIVE_COLOR = RED
BLUE_BTN_COLOR = BLACK
BLUE_BTN_BG_COLOR = BLUE
BLUE_BTN_BG_ACTIVE_COLOR = DARK_BLUE
DRAGGABLE_BG = DARK_YELLOW
