name: build
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    name: build-${{ matrix.platform }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [ win32, win64 ]
        include:
          - platform: win32
            arch: x86
          - platform: win64
            arch: x64
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        architecture: ${{ matrix.arch }}

    - name: Install dependencies
      run: |
        python -m pip install -U --force-reinstall pip
        pip install -e .

    - name: Build release
      run: |
        python packaging/build.py --os ${{ matrix.platform }}

    - name: Publish release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/until-zero-*.exe
